# 1. ETL and analysis for e-commerce big data

##### Jeff Guo; Aug 16, 2016; guojianfu@gmail.com

## 1.1 Working on missing data

Show sheet names of an excel:  
pd.ExcelFile("dognition_data_aggregated_by_dogid.xlsx").sheet_names  
pd is pandas, and xlrd is used by pandas to call ExcelFile method.

Produce a spreadsheet of an excel file:  
pd.ExcelFile("dognition_data_aggregated_by_dogid.xlsx").parse("dog_id_max_ranks")  
The result is a dataframe.
pd.read_csv() is to produce a spreadsheet of a csv file.
You can also convert a SQL table to a dataframe.

Dimentionality of a dataframe:  
pd.DataFrame(np.random.randn(10, 5)).shape  
The result ia a tuple.
np is numpy.
np.random.randn(10, 5) produeces an numpy ndarray of 10 by 5, and randn is for random variable of normal distribution.
shape is an attribution of the class DataFrame, to call this attribution may lead to the use of a method of the class.

True of False:  
pd.DataFrame(np.random.randn(10, 5)).isnull().values.any()

Total number of 'True':  
pd.DataFrame(np.random.randn(10, 5)).isnull().sum().sum()

True numbers of each column:  
pd.DataFrame(np.random.randn(10, 5)).isnull().sum()  
The result is a Series.

In [16]:
import numpy as np
import pandas as pd

a=np.random.randn(10, 5)
print a
print type(a)
b=pd.DataFrame(a)
print b
print type(b)
print b.head()
print b.dtypes
print b.columns.dtype
# np.int64
print b[0].dtype
# np.float64
c={'one':[1.,2.,3.,4.],\
   'two':[4.,3.,2.,1.]} # this line continuation backslash is optional
d=pd.DataFrame(c)
print d
e=pd.DataFrame(c, index=['a', 'b', 'c', 'd'])
print e
print type(e.index)
print e.index
f=pd.DataFrame(a, columns=['a', 'b', 'c', 'd', 'e'])
print f.columns
print pd.DataFrame(np.random.randn(10, 5)).isnull().values
s = pd.Series([1, 2, 3, np.NaN, 5, 6, None])
# np.NaN, None
print type(np.NaN)
print type(None)
print s.isnull()
print s[s.isnull()]

[[ 2.32510002  1.04323322 -0.08558535  0.67608167 -0.99733205]
 [ 0.11134467  1.08379484 -0.59866224 -0.2426094   1.5630922 ]
 [ 0.40053478 -1.30663622  0.60147257 -0.39861409 -1.79597582]
 [ 0.817556   -0.15613353  0.23174303  0.88264242 -1.16390871]
 [ 0.26423237  0.54386753  0.54113547 -0.52518831 -2.28785166]
 [ 0.65282798  1.80203722 -0.03137171  3.06453872  0.14353298]
 [-0.11546203 -0.02899987  1.59494904  0.80553879 -1.33033695]
 [ 0.38700001  2.24713983 -1.46505765  0.1400265   0.13370004]
 [-0.88731046  0.15412521 -0.49089381  0.41766859 -0.13241052]
 [-0.90403722  0.59011542 -0.71916389  0.93169312 -0.22183902]]
<type 'numpy.ndarray'>
          0         1         2         3         4
0  2.325100  1.043233 -0.085585  0.676082 -0.997332
1  0.111345  1.083795 -0.598662 -0.242609  1.563092
2  0.400535 -1.306636  0.601473 -0.398614 -1.795976
3  0.817556 -0.156134  0.231743  0.882642 -1.163909
4  0.264232  0.543868  0.541135 -0.525188 -2.287852
5  0.652828  1.802037 -0.031372  3

In [17]:
import pandas as pd
xl = pd.ExcelFile("dognition_data_aggregated_by_dogid.xlsx")
# xlrd is used by pandas
xl.sheet_names
df = xl.parse("dog_id_max_ranks")
# df.head()

print df.shape
print
print df.isnull().values.any()
print
print df.isnull().sum().sum()
print
print df.isnull().sum()

(17986, 30)

True

30500

Dog ID                                                0
Total Tests Completed                                 0
Mean ITI (days)                                    1268
Mean ITI (minutes)                                 1268
Median ITI (days)                                  1268
Median ITI (minutes)                               1268
Time diff between first and last game (days)          0
Time diff between first and last game (minutes)       0
User ID                                               1
Gender                                                1
Birthday                                              1
Breed                                                16
Breed_Type                                            1
Breed_Group                                           1
Weight                                                1
Dog_Fixed                                             1
DNA_Tested                                            1
Dimension             

Produce the dataframe:  
df=pd.ExcelFile("dognition_data_aggregated_by_dogid.xlsx").parse("dog_id_max_ranks")

True numbers of each row, too many rows:  
np.sum(df.isnull().values, axis = 1)

The range of Ture numbers for the rows:  
[min(np.sum(df.isnull().values, axis = 1)), max(np.sum(df.isnull().values, axis = 1))]

From a numpy ndarray to a list:  
num = np.sum(df.isnull().values, axis = 1).tolist()

Get unique values of the list and sort the list:  
l1 = list(set(num))
l1.sort()

list comprehension and put the results in a dict:  
fre = {i:num.count(i) for i in l1}  
count() is a method in the list class

Row counts for 'Number of NaNs', construct a dataframe from a dict:  
pd.DataFrame(fre.items(), columns=['Number of NaNs', 'Count'])  
Row index is row numbers.

In [18]:
import numpy as np

# np.ptp(np.sum(df.isnull().values, axis = 1), axis=0)
print [min(np.sum(df.isnull().values, axis = 1)), max(np.sum(df.isnull().values, axis = 1))]
print

num = np.sum(df.isnull().values, axis = 1).tolist()

l1 = list(set(num))
l1.sort()

fre = {i:num.count(i) for i in l1}
# print fre
# print

dt = pd.DataFrame(fre.items(), columns=['Number of NaNs', 'Count'])
# or list(fre.items()) in python 3

print dt

[0, 22]

   Number of NaNs  Count
0               0  11145
1               1     46
2               2     19
3               3     89
4               4   5832
5               5      8
6               7      9
7               8    837
8              22      1


We can draw and save tables to pictures in python.  
missingData.ipynb has the code to draw pictures.

We can also save json data and then apply the data to a html template with python to produce table in a webpage.

In [41]:
import numpy as np

x = [1, 2, 3]
y = [4, 5, 6]
zipped = zip(x, y)
print zipped
print type(zipped)
x2, y2 = zip(*zip(x, y))
# There are two ways to use *, one way is to use it as function parameter, and another way is
# to use it as function argument. It's the same to **, the differences are * is for list, while
# ** is for dict.
# If you have a list of arguments, *args, it's called "argument unpacking", 
# in the same manner **kwargs is called "keyword argument unpacking".
print type(x2)
print x == list(x2) and y == list(y2)
s=df.isnull().sum()
print type(s)
print s.name
print np.array(dt).tolist()
# np array and np ndarray
data_rows=np.array(dt).tolist()
dict_rows={x:y for x,y in data_rows}
print dict_rows

[(1, 4), (2, 5), (3, 6)]
<type 'list'>
<type 'tuple'>
True
<class 'pandas.core.series.Series'>
None
[[0, 11145], [1, 46], [2, 19], [3, 89], [4, 5832], [5, 8], [7, 9], [8, 837], [22, 1]]
{0: 11145, 1: 46, 2: 19, 3: 89, 4: 5832, 5: 8, 7: 9, 8: 837, 22: 1}


In [42]:
import json

s=df.isnull().sum()
s.tolist()
s.index.tolist()
data_columns=dict(zip(s.index.tolist(),s.tolist()))
print data_columns
# in python 2, there are strings and unicodes (utf-8).
with open('data_columns.json','w') as nnFile:
    json.dump(data_columns, nnFile)
# command+[
data_rows=np.array(dt).tolist()
with open('data_rows.json','w') as nnFile:
    json.dump(data_rows, nnFile)

{u'Membership_Type': 1, u'City': 6368, u'Subscribed': 1, u'Breed_Type': 1, u'Breed': 16, u'Membership_ID': 1, u'Last_Active_At': 1, u'State': 6363, u'Sign_in_Count': 1, u'Zip': 6396, u'Mean ITI (days)': 1268, u'User ID': 1, u'Country': 6268, u'Max_Dogs': 1, u'Median ITI (minutes)': 1268, u'Total Tests Completed': 0, u'Mean ITI (minutes)': 1268, u'Dog ID': 0, u'Gender': 1, u'DNA_Tested': 1, u'Dog_Fixed': 1, u'Exclude': 1, u'Breed_Group': 1, u'Dimension': 1, u'Free_Start_User': 1, u'Median ITI (days)': 1268, u'Weight': 1, u'Time diff between first and last game (minutes)': 0, u'Time diff between first and last game (days)': 0, u'Birthday': 1}
